#!/bin/bash

set -e

cd ../main
../tools/png_to_c_v2.pl -b ../pictures/pic_1.png imgv2_sha     imgv2_sha.c 
../tools/png_to_c_v2.pl -b ../pictures/pic_2.png imgv2_menu    imgv2_menu.c 
../tools/png_to_c_v2.pl -b ../pictures/pic_3.png imgv2_nick    imgv2_nick.c 
../tools/png_to_c_v2.pl -b ../pictures/pic_4.png imgv2_weather imgv2_weather.c 
../tools/png_to_c_v2.pl -b ../pictures/pic_5.png imgv2_test    imgv2_test.c 
