// This file is generated by SHA2017-badge/Firmware/ugfx/build_fonts.sh
#include "PermanentMarker22.c"
#include "PermanentMarker36.c"
#include "Roboto-Black22.c"
#include "Roboto-BlackItalic24.c"
#include "Roboto-Regular12.c"
#include "Roboto-Regular18.c"
#include "Roboto-Regular22.c"
